variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.6.3-jdk-11

cache:
  paths:
    - .m2/repository

.build: &build
  stage: build
  artifacts:
    paths:
      - "target/*"
      - "*/target/*"
  script:
    - 'mvn -Prelease $MAVEN_CLI_OPTS package'

.verify: &verify
  stage: test
  script:
    - 'mvn -Dmaven.main.skip $MAVEN_CLI_OPTS verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:jdk11:
  <<: *build

verify:jdk11:
  <<: *verify

deploy:jdk11:
  stage: deploy
  script:
    - 'mvn -Prelease -Dmaven.main.skip $MAVEN_CLI_OPTS deploy -s ${CI_SETTINGS_XML}'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - |
      for path in $(find . -iname "apidocs"); do
        mkdir -p public/$(echo $path | sed s@/target/@/@)
        cp -r $path/* public/$(echo $path | sed s@/target/@/@)
      done
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH